### ISSUE TITLE
Features tracking issue

### ISSUE THREAD

**Issue by overlookmotel** [overlookmotel/layout_inspect#1]
Quick TODO list:

* [ ] Support enum generics
* [ ] Support `&` refs in structs + enums
* [ ] Support nested refs in structs + enums e.g. `struct Foo<'a> { s: &'a &'a str }`
* [ ] Handle lifetime params on structs (include '&' in name on fields)
* [ ] Support tuples
* [ ] Support tuple structs `struct Foo (u8, u16)`
* [ ] Support unions
* [ ] Support `[T]` (cannot use `std::mem::align_of`)
* [ ] Support `[T; N]`
* [ ] Support unsized structs e.g. `struct Foo { s: str }` (#2)
* [ ] Allow deriving for unsized structs
* [ ] Deduce alignment for unsized types where possible e.g. `struct X { n: u64, s: str }`
* [ ] Rename `DefType` to `TypeDef`?
* [ ] Rename `.collect()` to `.inspect()`?
* [ ] Output span when macro errors
* [ ] Support more types (match those supported by serde)
